<span style="color:blue">DAY-16</span>

<span style="color:red;"><b> ordinal-label-encoding</b></span>

In [48]:
import numpy as np
import pandas as pd

In [49]:
data=pd.read_csv("E-commerce Customer Behavior - Sheet1.csv")

In [50]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Manual DataFrame
df = pd.DataFrame({'color': ['Red', 'Green', 'Blue', 'Green', 'Red']})

# Initialize encoder
encoder = OrdinalEncoder()

# Encode the 'color' column
encoded = encoder.fit_transform(df[['color']])

# Print encoded values
print(encoded)


[[2.]
 [1.]
 [0.]
 [1.]
 [2.]]


In [51]:
data.head(5)

Customer ID  Gender  Age           City Membership Type  Total Spend  \
0          101  Female   29       New York            Gold      1120.20   
1          102    Male   34    Los Angeles          Silver       780.50   
2          103  Female   43        Chicago          Bronze       510.75   
3          104    Male   30  San Francisco            Gold      1480.30   
4          105    Male   27          Miami          Silver       720.40   

   Items Purchased  Average Rating  Discount Applied  \
0               14             4.6              True   
1               11             4.1             False   
2                9             3.4              True   
3               19             4.7             False   
4               13             4.0              True   

   Days Since Last Purchase Satisfaction Level  
0                        25          Satisfied  
1                        18            Neutral  
2                        42        Unsatisfied  
3                        12          Satisfied  
4                        55        Unsatisfied

In [52]:
data.columns

Index(['Customer ID', 'Gender', 'Age', 'City', 'Membership Type',
       'Total Spend', 'Items Purchased', 'Average Rating', 'Discount Applied',
       'Days Since Last Purchase', 'Satisfaction Level'],
      dtype='object')

In [53]:
data = data[['Age', 'Gender', 'Items Purchased', 'Average Rating']]
print(data.head())


   Age  Gender  Items Purchased  Average Rating
0   29  Female               14             4.6
1   34    Male               11             4.1
2   43  Female                9             3.4
3   30    Male               19             4.7
4   27    Male               13             4.0


In [54]:
from sklearn.preprocessing import OrdinalEncoder

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x = data['Items Purchased']
y = data['Items Purchased']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [57]:
x_train

228    12
78     16
90     16
16     12
66     14
       ..
71      7
106    10
270    12
348    11
102    15
Name: Items Purchased, Length: 280, dtype: int64

In [58]:
oe = OrdinalEncoder()

In [65]:

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd


In [67]:
model = LinearRegression()
model.fit(x_train, y_train)

# Prediction
y_pred = model.predict(x_test)


mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")

RMSE: 1.65
R² Score: 0.85


In [68]:
from sklearn.preprocessing import LabelEncoder


In [69]:
le=LabelEncoder()

In [70]:
le.fit(y_train)

LabelEncoder()

In [71]:
le.classes_

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21])

In [77]:
y_train


array([ 5,  9,  9,  5,  7,  9,  5,  3,  0,  1,  4,  1, 12,  0,  1,  9,  1,
       13,  1,  4, 12,  1,  3,  8,  2,  2,  4,  7,  3,  1,  8,  5,  0,  1,
        4,  4,  4,  2,  7,  3,  2,  2,  6, 11,  3,  9, 13,  8,  3,  6,  1,
       13,  0, 12,  5, 10,  1,  8,  3,  3,  4,  2,  3, 12,  3,  5,  6,  5,
        1,  8,  2, 12,  3,  7,  0,  6,  4, 13,  3,  0,  4,  8,  2,  4,  6,
        3,  1,  2,  6,  2,  2,  7, 13, 10, 12,  1,  8,  0, 12, 12,  3,  0,
        6, 12,  6, 12,  6, 13,  1,  4,  3,  0,  2,  8,  4,  6,  5,  2,  5,
        2,  2,  0,  9,  1,  7, 11,  4,  2,  2,  1,  0, 12,  1,  2,  2,  5,
        6,  0,  2,  3,  1,  3,  5,  8,  6, 13,  9,  1,  3,  3,  6,  9,  9,
        0,  5, 12,  1,  0,  3,  4, 10,  0,  1,  3, 10,  3,  2,  5, 12,  6,
        6,  7,  6,  9,  8,  6,  0,  9,  4, 13,  6,  5, 12,  3,  7,  8,  6,
        1,  2, 11,  9, 13,  9, 13, 13,  9,  1,  9,  2, 13,  3,  3,  5,  2,
        8,  6, 13, 13,  5,  6, 10,  5, 12,  5,  9,  0,  2,  8,  7,  1,  5,
        2,  3,  2, 13,  0

<p style="color: purple; font-style: italic;">
  Encoding in Python is the process of converting text (usually Unicode) into bytes using a specific character set like UTF-8, ASCII, etc. This is particularly important when reading or writing files, sending data over networks, or working with APIs. Python provides built-in support for encoding using the <code>encode()</code> and <code>decode()</code> methods. The most common encoding used is UTF-8, which supports most characters and is widely compatible.
</p>
